### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/analyticalMachine#1]
A list of things that need to be finished:

- [ ] Gather English writings by Ada Lovelace (letters, correspondance, papers, etc.)
- [ ] Gather English writings by LF Menabrea (letters, correspondance, papers, etc.)
- [ ] Gather French writings by Ada Lovelace (letters, correspondance, papers, etc.)
- [ ] Gather French writings by LF Menabrea (letters, correspondance, papers, etc.)
- [ ] Run JGAAP over collected files
